# GitHub Action to run spine_items unit tests

name: Unit tests

# Run workflow on every push
on:
  push

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        python-version: [3.8, 3.9, "3.10", 3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run:
         python -c "import sys; print(sys.version)"
    - name: Install additional packages for Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libegl1
    - name: Install dependencies
      env:
        PYTHONUTF8: 1
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install coverage
        pip install codecov
    - name: List packages
      run:
        pip list
    - name: Run tests
      run: |
        if [ "$RUNNER_OS" != "Windows" ]; then
          export QT_QPA_PLATFORM=offscreen
        fi
        coverage run -m unittest discover --verbose
      shell: bash
    - name: Upload coverage report to Codecov
      run:
        codecov
